### ISSUE TITLE
Handle empty prediction GeoJSON

### ISSUE THREAD

**Issue by AdeelH** [azavea/foss4g-2022-hitl-groundwork-rastervision#24]
In some cases, the prediction GeoJSON produced by Raster Vision can be empty. This can happen for the following reasons:
- mediocre model
- no instances of the target class in the scene
- predictions are scattered and noisy and a large value of `denoise_radius` discards them.

(Note that despite the empty predictions, the priority scores for tasks still get populated correctly.)

Currently, this causes the job to fail at `merge_labels_with_task_grid()` with the following error:
```
INFO:Prediction labels location... s3://rasterfoundry-staging-hitl-output-us-east-1/d84e0495-825f-48fe-9f03-9a0e81d66c87/0/pred/pred.geojson
--
INFO:Processing the task grid and the labels...
Traceback (most recent call last):
File "/opt/conda/bin/hitl", line 11, in <module>
load_entry_point('hitl==0.1.0', 'console_scripts', 'hitl')()
File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 760, in invoke
return __callback(*args, **kwargs)
File "/opt/conda/lib/python3.7/site-packages/hitl-0.1.0-py3.7.egg/hitl/commands/run_hitl.py", line 97, in run_hitl
job_id
File "/opt/conda/lib/python3.7/site-packages/hitl-0.1.0-py3.7.egg/hitl/utils/post_process.py", line 10, in post_process
pred_geojson_uri
File "/opt/conda/lib/python3.7/site-packages/hitl-0.1.0-py3.7.egg/hitl/utils/post_process.py", line 25, in process_tasks
preds_gdf, tasks_to_update)
File "/opt/conda/lib/python3.7/site-packages/hitl-0.1.0-py3.7.egg/hitl/utils/merge_labels.py", line 5, in merge_labels_with_task_grid
return gpd.overlay(labels, task_grid, how='intersection', keep_geom_type=True)
File "/opt/conda/lib/python3.7/site-packages/geopandas/tools/overlay.py", line 307, in overlay
geom_type = df1.geom_type.iloc[0]
File "/opt/conda/lib/python3.7/site-packages/pandas/core/indexing.py", line 931, in __getitem__
return self._getitem_axis(maybe_callable, axis=axis)
File "/opt/conda/lib/python3.7/site-packages/pandas/core/indexing.py", line 1566, in _getitem_axis
self._validate_integer(key, axis)
File "/opt/conda/lib/python3.7/site-packages/pandas/core/indexing.py", line 1500, in _validate_integer
raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```

- Logs from failed job: https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Fbatch$252Fjob/log-events/jobStagingHitl$252Fdefault$252F5ebff019f27c41d98161e4a00c85abdf
- Empty predictions: `s3://rasterfoundry-staging-hitl-output-us-east-1/d84e0495-825f-48fe-9f03-9a0e81d66c87/0/pred/`

A solution might be as simple as skipping this function call if the predictions are empty.

**Comment by AdeelH** [comment]
Updating `geopandas` to version `0.10.2` seems to fix this particular problem.

**Comment by AdeelH** [comment]
Fix in this branch: https://github.com/raster-foundry/raster-foundry/tree/test/ah/fix-empty-pred

Needs to be tested.
